# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "ON")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "OFF")
SET(CPACK_BINARY_ZIP "OFF")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TBZ2;ZIP")
SET(CPACK_IGNORE_FILES "\\.hg.*;cppcheck-output;perform-cppcheck;build/;~$;Thumbs.db;\\.directory;\\.kdev4;\\.settings;\\.project;\\.cproject;\\.pydevproject")
SET(CPACK_INSTALLED_DIRECTORIES "D:/projekat/CEGUI/CEGUI-Stripped/cegui-0.8.4;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/cegui")
SET(CPACK_MODULE_PATH "D:/projekat/CEGUI/CEGUI-Stripped/cegui-0.8.4/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "cegui 0.8.4")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "cegui 0.8.4")
SET(CPACK_OUTPUT_CONFIG_FILE "D:/projekat/CEGUI/CEGUI-Stripped/cegui-0.8.4/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "D:/projekat/CEGUI/CEGUI-Stripped/cegui-0.8.4/README.md")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Crazy Eddie's Gui System")
SET(CPACK_PACKAGE_FILE_NAME "cegui-0.8.4")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "cegui 0.8.4")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "cegui 0.8.4")
SET(CPACK_PACKAGE_NAME "cegui")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "CEGUI team")
SET(CPACK_PACKAGE_VERSION "0.8.4")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "8")
SET(CPACK_PACKAGE_VERSION_PATCH "4")
SET(CPACK_RESOURCE_FILE_LICENSE "D:/projekat/CEGUI/CEGUI-Stripped/cegui-0.8.4/COPYING")
SET(CPACK_RESOURCE_FILE_README "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2;ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "\\.hg.*;cppcheck-output;perform-cppcheck;build/;~$;Thumbs.db;\\.directory;\\.kdev4;\\.settings;\\.project;\\.cproject;\\.pydevproject")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "D:/projekat/CEGUI/CEGUI-Stripped/cegui-0.8.4;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/projekat/CEGUI/CEGUI-Stripped/cegui-0.8.4/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "cegui-0.8.4")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "win32-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "4")
